---
- hosts: localhost
  connection: local

  tasks:
    - name: Git clone
      ansible.builtin.git:
        repo: https://github.com/tud7/bookzy_ansible.git
        dest: bookzy_ansible

    - name: Change to project directory
      ansible.builtin.shell: cd bookzy_ansible

    - name: Build and package maven build
      command: mvn compile war:war

